version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.17.1
    volumes:
      - ./front_envoy/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "80:80"
      - "9901:9901"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --log-level debug"

  service-one-envoy:
    image: envoyproxy/envoy-alpine:v1.17.1
    volumes:
      - ./service-one/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "9010:9010"
      - "9210:9210"
      - "9310:9310"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --log-level debug"

  service-one:
    build: service-one/
    ports:
    - "8010:8010"

  service-two-envoy:
    image: envoyproxy/envoy-alpine:v1.17.1
    volumes:
      - ./service-two/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "9020:9020"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --log-level debug"

  service-two:
    build: service-two/
    ports:
    - "8020:8020"

  service-three-envoy:
    image: envoyproxy/envoy-alpine:v1.17.1
    volumes:
      - ./service-three/envoy-config.yaml:/etc/envoy-config.yaml
    ports:
      - "9030:9030"
    command: "/usr/local/bin/envoy -c /etc/envoy-config.yaml --log-level debug"

  service-three:
    build: service-three/
    ports:
    - "8030:8030"  

  jaeger:
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "9411:9411"
      - "16686:16686"